# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshSearch < Formula
  desc "Fast command-line tool to search through your SSH config file"
  homepage "https://github.com/gido/ssh-search"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gido/ssh-search/releases/download/v2.0.1/ssh-search_2.0.1_Darwin_x86_64.tar.gz"
      sha256 "11d8e8c729abd6c81070dadbcdbfeba324add441f01ae62a343d2c6dbf28d716"

      define_method(:install) do
        bin.install "ssh-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gido/ssh-search/releases/download/v2.0.1/ssh-search_2.0.1_Darwin_arm64.tar.gz"
      sha256 "88b4338316cde683d649d6d7de592d61b4939f64f4ea23f4116f44f9883efaeb"

      define_method(:install) do
        bin.install "ssh-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gido/ssh-search/releases/download/v2.0.1/ssh-search_2.0.1_Linux_x86_64.tar.gz"
      sha256 "fcbd3fa57eda9da4939f3396907cb99bde09f560065ab68785548982748436e0"
      define_method(:install) do
        bin.install "ssh-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gido/ssh-search/releases/download/v2.0.1/ssh-search_2.0.1_Linux_arm64.tar.gz"
      sha256 "9f359f6802cbb812d8b2a725c22b8080dd14ef68260495eebb5e4f1d2b5234a6"
      define_method(:install) do
        bin.install "ssh-search"
      end
    end
  end

  test do
    system "#{bin}/ssh-search", "--version"
  end
end
