# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshSearch < Formula
  desc "Fast command-line tool to search through your SSH config file"
  homepage "https://github.com/gido/ssh-search"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gido/ssh-search/releases/download/v0.1.0/ssh-search_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "441ddd995277f6929b0d2aa639e50af7103773a0bf39d35e3109b521312639f4"

      def install
        bin.install "ssh-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gido/ssh-search/releases/download/v0.1.0/ssh-search_0.1.0_Darwin_arm64.tar.gz"
      sha256 "7825a470f9a2de3532f7b84bbffe8d11cf9b04363a2623839d8367b7b4d55d7c"

      def install
        bin.install "ssh-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gido/ssh-search/releases/download/v0.1.0/ssh-search_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a73a9693c10084569783f987dd6f099c63e52f7ad776b5ec1780506bf86596e9"
      def install
        bin.install "ssh-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gido/ssh-search/releases/download/v0.1.0/ssh-search_0.1.0_Linux_arm64.tar.gz"
      sha256 "b4bb6b76a4743527dd36fa12bc375b7d6a256d5918db08492566962cbe7375bb"
      def install
        bin.install "ssh-search"
      end
    end
  end

  test do
    system "#{bin}/ssh-search", "--version"
  end
end
